CREATE TABLE `college` (
  `id` int(5) unsigned NOT NULL AUTO_INCREMENT,
  `inst_id` varchar(128) NOT NULL,
  `inst_code` int(5) unsigned NOT NULL,
  `eng_name` varchar(128) NOT NULL,
  `jap_name` varchar(128) NOT NULL,
  `kana` varchar(128) NOT NULL,
  `school_code` int(5) unsigned NOT NULL,
  `area` varchar(128) NOT NULL,
  `pref` varchar(128) NOT NULL,
  `postal_code` varchar(128) NOT NULL,
  `access` varchar(128) NOT NULL,
  `instl_status` varchar(128) NOT NULL,
  `study1` int(5) unsigned NOT NULL,
  `study2` int(5) unsigned NOT NULL,
  `study3` int(5) unsigned NOT NULL,
  `study4` int(5) unsigned NOT NULL,
  `study5` int(5) unsigned NOT NULL,
  `study6` int(5) unsigned NOT NULL,
  `study7` int(5) unsigned NOT NULL,
  `study8` int(5) unsigned NOT NULL,
  `study9` int(5) unsigned NOT NULL,
  `study10` int(5) unsigned NOT NULL,
  `study11` int(5) unsigned NOT NULL,
  `study12` int(5) unsigned NOT NULL,
  `study13` int(5) unsigned NOT NULL,
  `study14` int(5) unsigned NOT NULL,
  `study15` int(5) unsigned NOT NULL,
  `study16` int(5) unsigned NOT NULL,
  `study17` int(5) unsigned NOT NULL,
  `sp_flg` int(5) unsigned NOT NULL,
  `jur_url` varchar(128) NOT NULL,
  `manabi_url` varchar(128) NOT NULL,
  `url1` varchar(128) DEFAULT NULL,
  `url2` varchar(128) NOT NULL,
  `url3` varchar(128) NOT NULL,
  `the_rnk` varchar(16) NOT NULL,
  `total_rnk` int(5) unsigned NOT NULL,
  `total_rnk_v` varchar(16) NOT NULL,
  `res_rnk` int(5) unsigned NOT NULL,
  `res_rnk_v` varchar(16) NOT NULL,
  `eng_rnk` int(5) unsigned NOT NULL,
  `eng_rnk_v` varchar(16) NOT NULL,
  `out_rnk` int(5) unsigned NOT NULL,
  `out_rnk_v` varchar(16) NOT NULL,
  `env_rnk` int(5) unsigned NOT NULL,
  `env_rnk_v` varchar(16) NOT NULL,
  `hokkaido-tohoku_rnk_v` varchar(16) NOT NULL,
  `kitakanto-koshinetsu_rnk_v` varchar(16) NOT NULL,
  `shutoken_rnk_v` varchar(16) NOT NULL,
  `hokuriku-tokai_rnk_v` varchar(16) NOT NULL,
  `kinki_rnk_v` varchar(16) NOT NULL,
  `chugoku-shikoku_rnk_v` varchar(16) NOT NULL,
  `kyushu-okinawa_rnk_v` varchar(16) NOT NULL,
  `manabi_rnk1` int(5) NOT NULL,
  `manabi_rnk2` varchar(16) NOT NULL,
  `manabi_rnk3` varchar(16) NOT NULL,
  `manabi_text` varchar(128) NOT NULL,
  `manabi_flag` int(5) NOT NULL,
  `manabi_option` varchar(128) NOT NULL,
  `rnk1` int(5) unsigned DEFAULT NULL,
  `rnk_v1` varchar(16) NOT NULL,
  `rnk2` int(5) unsigned NOT NULL,
  `rnk_v2` varchar(16) NOT NULL,
  `total_score` float(12,1) NOT NULL,
  `total_score_v` varchar(16) NOT NULL,
  `total_score_p` varchar(16) NOT NULL,
  `res_score` float(12,1) NOT NULL,
  `res_score_v` varchar(16) NOT NULL,
  `res_score_p` varchar(16) NOT NULL,
  `eng_score` float(12,1) NOT NULL,
  `eng_score_v` varchar(16) NOT NULL,
  `eng_score_p` varchar(16) NOT NULL,
  `out_score` float(12,1) NOT NULL,
  `out_score_v` varchar(16) NOT NULL,
  `out_score_p` varchar(16) NOT NULL,
  `env_score` float(12,1) NOT NULL,
  `env_score_v` varchar(16) NOT NULL,
  `env_score_p` varchar(16) NOT NULL,
  `fin_per_stu` float(12,1) NOT NULL,
  `fin_per_stu_v` varchar(16) NOT NULL,
  `fin_per_stu_p` varchar(16) DEFAULT NULL,
  `fac_per_stu` float(12,1) NOT NULL,
  `fac_per_stu_v` varchar(16) NOT NULL,
  `fac_per_stu_p` varchar(16) DEFAULT NULL,
  `biblio` float(12,1) NOT NULL,
  `biblio_v` varchar(16) NOT NULL,
  `biblio_p` varchar(16) DEFAULT NULL,
  `mock_exam` float(12,1) NOT NULL,
  `mock_exam_v` varchar(16) NOT NULL,
  `mock_exam_p` varchar(16) DEFAULT NULL,
  `funding` float(12,1) NOT NULL,
  `funding_v` varchar(16) NOT NULL,
  `funding_p` varchar(16) DEFAULT NULL,
  `global` float(12,1) NOT NULL,
  `global_v` varchar(16) NOT NULL,
  `global_p` varchar(16) DEFAULT NULL,
  `ability` float(12,1) NOT NULL,
  `ability_v` varchar(16) NOT NULL,
  `ability_p` varchar(16) DEFAULT NULL,
  `emp_rep` float(12,1) NOT NULL,
  `emp_rep_v` varchar(16) NOT NULL,
  `emp_rep_p` varchar(16) DEFAULT NULL,
  `rep` float(12,1) NOT NULL,
  `rep_v` varchar(16) NOT NULL,
  `rep_p` varchar(16) DEFAULT NULL,
  `int_stu` float(12,1) NOT NULL,
  `int_stu_v` varchar(16) NOT NULL,
  `int_stu_p` varchar(16) NOT NULL,
  `int_staff` float(12,1) NOT NULL,
  `int_staff_v` varchar(16) NOT NULL,
  `int_staff_p` varchar(16) DEFAULT NULL,
  `study_abroad_long` float(12,1) NOT NULL,
  `study_abroad_long_v` varchar(16) NOT NULL,
  `study_abroad_long_p` varchar(16) NOT NULL,
  `study_abroad_short` float(12,1) NOT NULL,
  `study_abroad_short_v` varchar(16) NOT NULL,
  `study_abroad_short_p` varchar(16) NOT NULL,
  `all_english` float(12,1) NOT NULL,
  `all_english_v` varchar(16) NOT NULL,
  `all_english_p` varchar(16) NOT NULL,
  `active_learning` float(12,1) NOT NULL,
  `active_learning_v` varchar(16) NOT NULL,
  `active_learning_p` varchar(16) NOT NULL,
  `career_decision` float(12,1) NOT NULL,
  `career_decision_v` varchar(16) NOT NULL,
  `career_decision_p` varchar(16) NOT NULL,
  `opt1` varchar(128) NOT NULL,
  `opt2` varchar(128) NOT NULL,
  `opt3` varchar(128) NOT NULL,
  `opt4` varchar(128) NOT NULL,
  `opt5` varchar(128) NOT NULL,
  `text1` varchar(1024) NOT NULL,
  `text2` varchar(1024) NOT NULL,
  `text3` varchar(1024) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6069 DEFAULT CHARSET=utf8;
